{
  "schema_version": "1.2.0",
  "id": "GHSA-8p2c-fghc-9hj4",
  "modified": "2022-05-17T05:47:38Z",
  "published": "2022-05-17T05:47:38Z",
  "aliases": [
    "CVE-2008-7264"
  ],
  "details": "The ftp_QUIT function in ftpserver.py in pyftpdlib before 0.5.0 allows remote authenticated users to cause a denial of service (file descriptor exhaustion and daemon outage) by sending a QUIT command during a disallowed data-transfer attempt.",
  "severity": [

  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2008-7264"
    },
    {
      "type": "WEB",
      "url": "http://code.google.com/p/pyftpdlib/issues/detail?id=71"
    },
    {
      "type": "WEB",
      "url": "http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY"
    },
    {
      "type": "WEB",
      "url": "http://code.google.com/p/pyftpdlib/source/detail?r=344"
    },
    {
      "type": "WEB",
      "url": "http://code.google.com/p/pyftpdlib/source/diff?spec=svn344&r=344&format=side&path=/trunk/pyftpdlib/ftpserver.py"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-20"
    ],
    "severity": "MODERATE",
    "github_reviewed": false
  }
}