{
  "schema_version": "1.4.0",
  "id": "GHSA-8fww-64cx-x8p5",
  "modified": "2023-03-26T21:30:23Z",
  "published": "2023-03-26T21:30:23Z",
  "aliases": [
    "CVE-2023-28859"
  ],
  "details": "redis-py through 4.5.3 leaves a connection open after canceling an async Redis command at an inopportune time (in the case of a non-pipeline operation), and can send response data to the client of an unrelated request. NOTE: this issue exists because of an incomplete fix for CVE-2023-28858.",
  "severity": [

  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-28859"
    },
    {
      "type": "WEB",
      "url": "https://github.com/redis/redis-py/issues/2665"
    },
    {
      "type": "WEB",
      "url": "https://github.com/redis/redis-py/pull/2641"
    }
  ],
  "database_specific": {
    "cwe_ids": [

    ],
    "severity": null,
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2023-03-26T19:15:00Z"
  }
}