{
  "schema_version": "1.2.0",
  "id": "GHSA-h7f6-hc46-frrv",
  "modified": "2022-08-24T00:00:31Z",
  "published": "2022-08-24T00:00:31Z",
  "aliases": [
    "CVE-2021-28861"
  ],
  "details": "Python 3.x through 3.10 has an open redirection vulnerability in lib/http/server.py due to no protection against multiple (/) at the beginning of URI path which may leads to information disclosure.",
  "severity": [

  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-28861"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python/cpython/pull/24848"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python/cpython/pull/93879"
    },
    {
      "type": "WEB",
      "url": "https://bugs.python.org/issue43223"
    }
  ],
  "database_specific": {
    "cwe_ids": [

    ],
    "severity": null,
    "github_reviewed": false
  }
}