{
  "schema_version": "1.2.0",
  "id": "GHSA-g3p5-fjj9-h8gj",
  "modified": "2022-05-13T01:11:25Z",
  "published": "2022-05-13T01:11:25Z",
  "aliases": [
    "CVE-2013-1629"
  ],
  "details": "pip before 1.3 uses HTTP to retrieve packages from the PyPI repository, and does not perform integrity checks on package contents, which allows man-in-the-middle attackers to execute arbitrary code via a crafted response to a \"pip install\" operation.",
  "severity": [

  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2013-1629"
    },
    {
      "type": "WEB",
      "url": "https://github.com/pypa/pip/issues/425"
    },
    {
      "type": "WEB",
      "url": "https://github.com/pypa/pip/pull/791/files"
    },
    {
      "type": "WEB",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=968059"
    },
    {
      "type": "WEB",
      "url": "http://www.pip-installer.org/en/latest/installing.html"
    },
    {
      "type": "WEB",
      "url": "http://www.pip-installer.org/en/latest/news.html#changelog"
    },
    {
      "type": "WEB",
      "url": "http://www.reddit.com/r/Python/comments/17rfh7/warning_dont_use_pip_in_an_untrusted_network_a/"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-20"
    ],
    "severity": "MODERATE",
    "github_reviewed": false
  }
}