{
  "schema_version": "1.3.0",
  "id": "GHSA-vw39-2wj9-4q86",
  "modified": "2022-10-11T19:00:29Z",
  "published": "2022-10-11T19:00:29Z",
  "aliases": [
    "CVE-2022-42731"
  ],
  "details": "mfa/FIDO2.py in django-mfa2 before 2.5.1 and 2.6.x before 2.6.1 allows a replay attack that could be used to register another device for a user. The device registration challenge is not invalidated after usage.",
  "severity": [

  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-42731"
    },
    {
      "type": "WEB",
      "url": "https://github.com/mkalioby/django-mfa2/blob/0936ea253354dd95cb127f09d0efa31324caef27/mfa/FIDO2.py#L58"
    },
    {
      "type": "WEB",
      "url": "https://github.com/mkalioby/django-mfa2/releases/tag/v2.5.1-release"
    },
    {
      "type": "WEB",
      "url": "https://github.com/mkalioby/django-mfa2/releases/tag/v2.6.1-release"
    }
  ],
  "database_specific": {
    "cwe_ids": [

    ],
    "severity": null,
    "github_reviewed": false
  }
}