{
  "schema_version": "1.2.0",
  "id": "GHSA-chqf-hx79-gxc6",
  "modified": "2022-05-17T02:58:54Z",
  "published": "2022-05-17T02:58:54Z",
  "aliases": [
    "CVE-2017-5992"
  ],
  "details": "Openpyxl 2.4.1 resolves external entities by default, which allows remote attackers to conduct XXE attacks via a crafted .xlsx document.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:C/C:H/I:N/A:H"
    }
  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2017-5992"
    },
    {
      "type": "WEB",
      "url": "https://bitbucket.org/openpyxl/openpyxl/commits/3b4905f428e1"
    },
    {
      "type": "WEB",
      "url": "https://bitbucket.org/openpyxl/openpyxl/issues/749"
    },
    {
      "type": "WEB",
      "url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854442"
    },
    {
      "type": "WEB",
      "url": "http://www.openwall.com/lists/oss-security/2017/02/07/5"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-611"
    ],
    "severity": "HIGH",
    "github_reviewed": false
  }
}