{
  "schema_version": "1.3.0",
  "id": "GHSA-h4rr-269p-4557",
  "modified": "2022-03-17T00:06:09Z",
  "published": "2022-01-27T00:00:54Z",
  "aliases": [
    "CVE-2022-0368"
  ],
  "details": "Out-of-bounds Read in Conda vim prior to 8.2.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
    }
  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-0368"
    },
    {
      "type": "WEB",
      "url": "https://github.com/vim/vim/commit/8d02ce1ed75d008c34a5c9aaa51b67cbb9d33baa"
    },
    {
      "type": "WEB",
      "url": "https://huntr.dev/bounties/bca9ce1f-400a-4bf9-9207-3f3187cb3fa9"
    },
    {
      "type": "WEB",
      "url": "https://lists.debian.org/debian-lts-announce/2022/03/msg00018.html"
    },
    {
      "type": "WEB",
      "url": "https://security.gentoo.org/glsa/202208-32"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-125"
    ],
    "severity": "HIGH",
    "github_reviewed": false
  }
}