{
  "schema_version": "1.4.0",
  "id": "GHSA-24wv-mv5m-xv4h",
  "modified": "2023-03-26T21:30:23Z",
  "published": "2023-03-26T21:30:23Z",
  "aliases": [
    "CVE-2023-28858"
  ],
  "details": "redis-py before 4.5.3, as used in ChatGPT and other products, leaves a connection open after canceling an async Redis command at an inopportune time (in the case of a pipeline operation), and can send response data to the client of an unrelated request in an off-by-one manner. The fixed versions for this CVE Record are 4.3.6, 4.4.3, and 4.5.3; however, CVE-2023-28859 is a separate vulnerability.",
  "severity": [

  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-28858"
    },
    {
      "type": "WEB",
      "url": "https://github.com/redis/redis-py/issues/2624"
    },
    {
      "type": "WEB",
      "url": "https://github.com/redis/redis-py/pull/2641"
    },
    {
      "type": "WEB",
      "url": "https://github.com/redis/redis-py/compare/v4.3.5...v4.3.6"
    },
    {
      "type": "WEB",
      "url": "https://github.com/redis/redis-py/compare/v4.4.2...v4.4.3"
    },
    {
      "type": "WEB",
      "url": "https://github.com/redis/redis-py/compare/v4.5.2...v4.5.3"
    },
    {
      "type": "WEB",
      "url": "https://openai.com/blog/march-20-chatgpt-outage"
    }
  ],
  "database_specific": {
    "cwe_ids": [

    ],
    "severity": null,
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2023-03-26T19:15:00Z"
  }
}