{
  "schema_version": "1.4.0",
  "id": "GHSA-pvw5-cvp6-cv92",
  "modified": "2023-08-22T21:30:27Z",
  "published": "2023-08-22T21:30:27Z",
  "aliases": [
    "CVE-2022-48560"
  ],
  "details": "A use-after-free exists in Python through 3.9 via heappushpop in heapq.",
  "severity": [

  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-48560"
    },
    {
      "type": "WEB",
      "url": "https://bugs.python.org/issue39421"
    }
  ],
  "database_specific": {
    "cwe_ids": [

    ],
    "severity": null,
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": null
  }
}