{
  "schema_version": "1.3.0",
  "id": "GHSA-44mv-gf6j-pvgx",
  "modified": "2022-12-18T06:31:09Z",
  "published": "2022-12-18T06:31:09Z",
  "aliases": [
    "CVE-2022-47515"
  ],
  "details": "An issue was discovered in drachtio-server before 0.8.20. It allows remote attackers to cause a denial of service (daemon crash) via a long message in a TCP request that leads to std::length_error.",
  "severity": [

  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-47515"
    },
    {
      "type": "WEB",
      "url": "https://github.com/drachtio/drachtio-server/issues/245"
    },
    {
      "type": "WEB",
      "url": "https://github.com/drachtio/drachtio-server/commit/4cf9fe2c420b86c16442215d449d40be777c1911"
    }
  ],
  "database_specific": {
    "cwe_ids": [

    ],
    "severity": null,
    "github_reviewed": false
  }
}