{
  "schema_version": "1.2.0",
  "id": "GHSA-rwqr-c348-m5wr",
  "modified": "2022-06-25T07:22:37Z",
  "published": "2022-06-24T00:00:31Z",
  "aliases": [
    "CVE-2022-33124"
  ],
  "summary": "Denial of Service in aiohttp",
  "details": "aiohttp v3.8.1 was discovered to contain an invalid IPv6 URL which can lead to a Denial of Service (DoS).",
  "severity": [

  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "aiohttp"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            }
          ]
        }
      ],
      "database_specific": {
        "last_known_affected_version_range": "<= 3.8.1"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-33124"
    },
    {
      "type": "WEB",
      "url": "https://github.com/aio-libs/aiohttp/issues/6772"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/aio-libs/aiohttp"
    }
  ],
  "database_specific": {
    "cwe_ids": [

    ],
    "severity": "MODERATE",
    "github_reviewed": true
  }
}